export INFLUXDB_TOKEN=${INFLUXDB_TOKEN:="k6"}
export INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD:='changeMe'}
export INFLUXDB_HOST=${INFLUXDB_HOST:='http://localhost'}
export INFLUXDB_PORT=${INFLUXDB_PORT:='8086'}
export INFLUXDB_USERNAME=${INFLUXDB_USERNAME:='k6'}
export INFLUXDB_BUCKET=${INFLUXDB_BUCKET:='k6'}
export INFLUXDB_ORG=${INFLUXDB_ORG:='k6'}
export INFLUXDB_RETENTION=${INFLUXDB_RETENTION:='0'}
export K6_VIRTUAL_USER_COUNT=${K6_VIRTUAL_USER_COUNT:='1000'}
export K6_TEST_DURATION=${K6_TEST_DURATION:='2m'}
export K6_OUTPUT_INTEGRATION=${K6_OUTPUT_INTEGRATION:='xk6-influxdb'}

K6_INFLUXDB_ORGANIZATION=${INFLUXDB_ORG} \
K6_INFLUXDB_BUCKET=${INFLUXDB_BUCKET} \
K6_INFLUXDB_TOKEN=${INFLUXDB_TOKEN} \
K6_INFLUXDB_ADDR=${INFLUXDB_HOST}:${INFLUXDB_PORT} \
k6 run --vus ${K6_VIRTUAL_USER_COUNT} --duration ${K6_TEST_DURATION} /test_scripts/test.js -o ${K6_OUTPUT_INTEGRATION} -o xk6-influxdb

bash
